version: '3.4'

services:
  backend:
    image: docker.pkg.github.com/univ-smb-m1-isc-2020/bande-dessinee-fr/bande-dessinee-fr-backend:latest
    restart: always
    ports:
      - 6568:80
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    depends_on:
    - db


  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on:
      - db
volumes:
  db-data:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
    
