CREATE TABLE movie (
	id serial PRIMARY KEY,
	api_detail_url   VARCHAR ( 50 ),
    dox_office_revenue VARCHAR ( 50 ),
    dudget VARCHAR ( 50 ),
    date_added VARCHAR ( 50 ),
    date_last_updated VARCHAR ( 50 ),
    deck VARCHAR ( 50 ),
    description_ VARCHAR ( 50 ),
    distributor VARCHAR ( 50 ),
    has_staff_review VARCHAR ( 50 ),
    image VARCHAR ( 50 ),
    name VARCHAR ( 50 ),
    producers VARCHAR ( 50 ),
    rating VARCHAR ( 50 ),
    release_date VARCHAR ( 50 ),
    runtime VARCHAR ( 50 ),
    site_detail_url VARCHAR ( 50 ),
    studios VARCHAR ( 50 ),
    total_revenue VARCHAR ( 50 ),
    writers VARCHAR ( 50 )
);
